version: '3.8'

volumes:
  kestra_postgres_data:
    driver: local
  kestra_data:
    driver: local

services:
  kestra_postgres:
    image: postgres:15
    volumes:
      - kestra_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
      # For Codespaces compatibility:
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
      - PGADMIN_CONFIG_WTF_CSRF_ENABLED=False
      - PGADMIN_CONFIG_WTF_CSRF_SSL_STRICT=False
      - PGADMIN_CONFIG_WTF_CSRF_TIME_LIMIT=None
      - PGADMIN_CONFIG_PROXY_X_FOR_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PROTO_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_HOST_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PORT_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT=1
    ports:
      - "8085:80"

  kestra:
    image: kestra/kestra:v0.18.3
    command: server standalone
    volumes:
      - kestra_data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    environment:
      KESTRA_CONFIGURATION: |
        kestra:
          repository:
            type: postgres
          storage:
            type: local
            local:
              basePath: "/app/storage"
          queue:
            type: postgres
          plugins:
            configurations:
              - type: io.kestra.plugin.scripts.runner.docker.Docker
                values:
                  volume-enabled: true
        datasources:
          postgres:
            url: jdbc:postgresql://kestra_postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
    ports:
      - "8080:8080"
    depends_on:
      kestra_postgres:
        condition: service_healthy
    restart: on-failure:5
